//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 05:39:12 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.titanic.com/spring/soap/api/titanicSurvival", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.titanic.spring.soap.api.titanicsurvival;
